import { Exercise, GymEnvironment, MuscleGroup } from '../types';

export const EXERCISE_DATABASE: Exercise[] = [
  // --- SQUAT PATTERN (Quadríceps / Glúteos) ---
  {
    id: 'ex_squat_barbell',
    nome: 'Agachamento Livre com Barra',
    nomeEnglish: 'Barbell Back Squat',
    grupoMuscular: 'quadriceps',
    musculosSecundarios: ['gluteos', 'core', 'posteriores'],
    categoria: 'compound',
    equipamento: 'barbell',
    nivel: 'intermediate',
    tipoMovimento: 'legs',
    padraoMotor: 'squat',
    planoMovimento: 'sagittal',
    execucao: 'Pés na largura dos ombros, barra apoiada no trapézio médio, agachar até ultrapassar a linha dos joelhos mantendo coluna neutra e joelhos alinhados aos pés.',
    passoAPasso: [
      '1. Posicione a barra no suporte na altura do peitoral superior.',
      '2. Entre debaixo da barra, apoiando-a sobre o trapézio médio, e retire-a do suporte dando dois passos para trás.',
      '3. Posicione os pés ligeiramente mais abertos que a largura dos ombros, com as pontas viradas levemente para fora (15-30°).',
      '4. Inspire profundamente e estabilize o core com a manobra de Valsalva.',
      '5. Inicie o movimento flexionando simultaneamente joelhos e quadril, descendo com controle técnico.',
      '6. Desça até que a linha do quadril fique abaixo do topo dos joelhos.',
      '7. Empurre o chão com força total estendendo joelhos e quadril até retornar à posição inicial erecta.'
    ],
    objetivo: 'Desenvolvimento maximal de hipertrofia nos quadríceps, glúteos e força estrutural dos membros inferiores.',
    dicaPrincipal: 'Mantenha o peito aberto e os joelhos sempre apontando exatamente na mesma direção das pontas dos pés.',
    respiracao: 'Inspire profundamente e faça a manobra de Valsalva na descida, expire ao passar pelo ponto crítico de subida.',
    amplitude: 'Completa (quadril abaixo do nível do joelho - profundidade válida sem retroversão pélvica).',
    cadencia: '3-1-1-0',
    rir: 2,
    rpe: 8,
    descanso: 150,
    video: 'https://www.youtube-nocookie.com/embed/ultWZbUMPL8',
    youtubeVideoId: 'ultWZbUMPL8',
    imagemAnatomica3D: '/images/athletic_squat_3d_1786105958653.jpg',
    errosComuns: ['Valgo dinâmico nos joelhos', 'Retroversão pélvica excessiva (butt wink)', 'Elevação prematura do quadril na subida'],
    variacoes: ['Agachamento Frontal', 'Agachamento Barra Baixa', 'Agachamento Pausado'],
    substitutos: [
      { originalId: 'ex_squat_barbell', replacementId: 'ex_leg_press_45', replacementName: 'Leg Press 45°', condition: 'small_gym', equivalenceScore: 90, notes: 'Substituição excelente para isolar membros inferiores reduzindo carga axial na coluna.' },
      { originalId: 'ex_squat_barbell', replacementId: 'ex_goblet_squat', replacementName: 'Agachamento Goblet com Halter', condition: 'home', equivalenceScore: 85, notes: 'Substituição segura com halteres ou kettlebell.' },
      { originalId: 'ex_squat_barbell', replacementId: 'ex_hack_squat', replacementName: 'Agachamento Hack Máquina', condition: 'full_gym', equivalenceScore: 92, notes: 'Permite falha segura com suporte nas costas.' }
    ],
    fatigueIndex: 5
  },
  {
    id: 'ex_hack_squat',
    nome: 'Agachamento Hack Máquina',
    nomeEnglish: 'Hack Squat Machine',
    grupoMuscular: 'quadriceps',
    musculosSecundarios: ['gluteos'],
    categoria: 'compound',
    equipamento: 'machine',
    nivel: 'beginner',
    tipoMovimento: 'legs',
    padraoMotor: 'squat',
    planoMovimento: 'sagittal',
    execucao: 'Costas bem apoiadas no encosto, pés na plataforma. Flexione joelhos conduzindo quadril profundamente com estabilidade.',
    passoAPasso: [
      '1. Encoste as costas e os ombros firmemente nas almofadas do Hack.',
      '2. Posicione os pés na plataforma na largura do quadril.',
      '3. Destrave a trava de segurança da máquina segurando as manoplas laterais.',
      '4. Desça flexionando os joelhos de forma controlada até ~90° ou mais de profundidade.',
      '5. Mantenha os calcanhares apoiados e empurre a plataforma para estender os joelhos.',
      '6. Retorne à posição inicial sem travar ou hiperextender os joelhos no topo.'
    ],
    objetivo: 'Hipertrofia focada no quadríceps com suporte lombar e estabilidade guiada por trilhos.',
    dicaPrincipal: 'Não deixe a lombar descolar do encosto no ponto mais profundo da descida.',
    respiracao: 'Inspire na descida excêntrica, expire na extensão concêntrica.',
    amplitude: 'Máxima amplitude mecânica sem descolar a lombar do encosto.',
    cadencia: '3-0-1-0',
    rir: 1,
    rpe: 9,
    descanso: 120,
    video: 'https://www.youtube-nocookie.com/embed/0tn5K9NlCfo',
    youtubeVideoId: '0tn5K9NlCfo',
    imagemAnatomica3D: '/images/athletic_squat_3d_1786105958653.jpg',
    errosComuns: ['Pés posicionados alto demais diminuindo momento no quadríceps', 'Tirar lombar do encosto'],
    variacoes: ['Hack Reverse', 'Hack V-Squat'],
    substitutos: [
      { originalId: 'ex_hack_squat', replacementId: 'ex_squat_barbell', replacementName: 'Agachamento Livre com Barra', condition: 'small_gym', equivalenceScore: 95, notes: 'Substitui a máquina por pesos livres.' },
      { originalId: 'ex_hack_squat', replacementId: 'ex_leg_press_45', replacementName: 'Leg Press 45°', condition: 'small_gym', equivalenceScore: 90, notes: 'Excelente estabilização mecânica equivalente.' }
    ],
    fatigueIndex: 4
  },
  {
    id: 'ex_leg_press_45',
    nome: 'Leg Press 45°',
    nomeEnglish: '45° Leg Press',
    grupoMuscular: 'quadriceps',
    musculosSecundarios: ['gluteos'],
    categoria: 'compound',
    equipamento: 'machine',
    nivel: 'beginner',
    tipoMovimento: 'legs',
    padraoMotor: 'squat',
    planoMovimento: 'sagittal',
    execucao: 'Pés alinhados na plataforma na largura do quadril, destravar o carrinho e descer flexionando joelhos até ~90° ou mais sem rodar a pelvis.',
    passoAPasso: [
      '1. Sente-se no aparelho mantendo o quadril e a lombar encostados no assento.',
      '2. Coloque os pés no centro da plataforma na largura dos ombros.',
      '3. Empurre a plataforma ligeiramente para destravar as travas de segurança.',
      '4. Flexione os joelhos trazendo a plataforma em direção ao tronco com cadência lenta.',
      '5. Interrompa a descida logo antes da pelvis começar a rodar para trás (retroversão).',
      '6. Empurre o peso com a planta inteira dos pés até retornar à posição inicial.'
    ],
    objetivo: 'Sobrecarga de volume seguro e hipertrofia de quadríceps sem estresse vertebral.',
    dicaPrincipal: 'Evite estender totalmente os joelhos no topo para manter o quadríceps sob tensão constante.',
    respiracao: 'Inspire na flexão de joelhos, expire na extensão.',
    amplitude: 'Até próximo da rotação pélvica posterior.',
    cadencia: '2-1-1-0',
    rir: 2,
    rpe: 8,
    descanso: 120,
    video: 'https://www.youtube-nocookie.com/embed/IZxyjW7MPJQ',
    youtubeVideoId: 'IZxyjW7MPJQ',
    imagemAnatomica3D: '/images/athletic_squat_3d_1786105958653.jpg',
    errosComuns: ['Bloqueio articular rígido dos joelhos no topo', 'Retroversão pélvica'],
    variacoes: ['Leg Press Unilateral', 'Leg Press Horizontal'],
    substitutos: [
      { originalId: 'ex_leg_press_45', replacementId: 'ex_goblet_squat', replacementName: 'Agachamento Goblet', condition: 'home', equivalenceScore: 85, notes: 'Substituição viável com halter ou peso corporal acelerado.' }
    ],
    fatigueIndex: 3
  },
  {
    id: 'ex_goblet_squat',
    nome: 'Agachamento Goblet com Halter',
    nomeEnglish: 'Dumbbell Goblet Squat',
    grupoMuscular: 'quadriceps',
    musculosSecundarios: ['gluteos', 'core'],
    categoria: 'compound',
    equipamento: 'dumbbell',
    nivel: 'beginner',
    tipoMovimento: 'legs',
    padraoMotor: 'squat',
    planoMovimento: 'sagittal',
    execucao: 'Segurar o halter junto ao tórax, agachar projetando cotovelos por dentro dos joelhos.',
    passoAPasso: [
      '1. Segure um halter em posição vertical junto ao peito com ambas as mãos apoiadas na cabeça superior da carga.',
      '2. Mantenha os pés afastados na largura dos ombros e o abdômen contraído.',
      '3. Inicie o agachamento jogando o quadril levemente para trás e flexionando os joelhos.',
      '4. Desça até que os cotovelos toquem ou passem por dentro dos joelhos.',
      '5. Empurre o chão com os calcanhares mantendo a coluna verticalizada.',
      '6. Finalize o movimento na posição em pé com glúteos ativos.'
    ],
    objetivo: 'Aprazamento técnico do padrão de agachamento e fortalecimento dos quadríceps com peso livre.',
    dicaPrincipal: 'Use a carga frontal como contrapesamento natural para manter o tronco vertical.',
    respiracao: 'Inspire na descida, expire ao subir.',
    amplitude: 'Profunda e fluida.',
    cadencia: '3-0-1-0',
    rir: 2,
    rpe: 8,
    descanso: 90,
    video: 'https://www.youtube-nocookie.com/embed/MeIiIdhvKL4',
    youtubeVideoId: 'MeIiIdhvKL4',
    imagemAnatomica3D: '/images/athletic_squat_3d_1786105958653.jpg',
    errosComuns: ['Inclinar o tronco para frente', 'Soltar a carga para longe do corpo'],
    variacoes: ['Goblet Squat na Prancha', 'Goblet Squat com Kettlebell'],
    substitutos: [],
    fatigueIndex: 2
  },

  // --- HINGE PATTERN (Posteriores & Glúteos) ---
  {
    id: 'ex_stiff_barbell',
    nome: 'Stiff com Barra (Levantamento Romeno)',
    nomeEnglish: 'Barbell Romanian Deadlift (RDL)',
    grupoMuscular: 'posteriores',
    musculosSecundarios: ['gluteos', 'core'],
    categoria: 'compound',
    equipamento: 'barbell',
    nivel: 'intermediate',
    tipoMovimento: 'legs',
    padraoMotor: 'hinge',
    planoMovimento: 'sagittal',
    execucao: 'Projetar o quadril para trás mantendo joelhos levemente destravados e barra rente às coxas até sentir máximo alongamento dos isquiotibiais.',
    passoAPasso: [
      '1. Segure a barra na largura dos ombros com pegada pronada.',
      '2. Fique em pé com os pés na largura do quadril e joelhos levemente destravados (15° de flexão).',
      '3. Projete o quadril para trás (movimento de flexão de quadril/hinge) mantendo a coluna neutra.',
      '4. Desça a barra rente às pernas até sentir forte alongamento no posterior da coxa (geralmente abaixo do joelho).',
      '5. Contraia os glúteos e posteriores para empurrar o quadril à frente e retornar à posição inicial erecta.'
    ],
    objetivo: 'Hipertrofia e força máxima nos isquiotibiais (posteriores) e glúteos em posição de alongamento mecânico.',
    dicaPrincipal: 'O movimento é horizontal de quadril para trás — não flexione os joelhos durante a descida!',
    respiracao: 'Inspire enquanto flete o quadril para trás, expire ao retornar estendendo o quadril.',
    amplitude: 'Até a linha abaixo do joelho (respeitando flexibilidade sem curvar a coluna).',
    cadencia: '3-1-1-0',
    rir: 2,
    rpe: 8,
    descanso: 120,
    video: 'https://www.youtube-nocookie.com/embed/_oyxCn2iSjU',
    youtubeVideoId: '_oyxCn2iSjU',
    imagemAnatomica3D: '/images/athletic_hinge_3d_1786106034930.jpg',
    errosComuns: ['Flexionar joelhos em demasia (virando agachamento)', 'Arredondar a coluna torácica e lombar'],
    variacoes: ['Stiff com Halteres', 'RDL Unilateral (Single Leg)'],
    substitutos: [
      { originalId: 'ex_stiff_barbell', replacementId: 'ex_stiff_dumbbell', replacementName: 'Stiff com Halteres', condition: 'small_gym', equivalenceScore: 98, notes: 'Permite pegada mais neutra e menor estresse nos punhos.' },
      { originalId: 'ex_stiff_barbell', replacementId: 'ex_lying_leg_curl', replacementName: 'Mesa Flexora', condition: 'small_gym', equivalenceScore: 85, notes: 'Excelente isolamento da flexão de joelhos se o quadril estiver fadigado.' }
    ],
    fatigueIndex: 4
  },
  {
    id: 'ex_stiff_dumbbell',
    nome: 'Stiff com Halteres',
    nomeEnglish: 'Dumbbell RDL',
    grupoMuscular: 'posteriores',
    musculosSecundarios: ['gluteos', 'core'],
    categoria: 'compound',
    equipamento: 'dumbbell',
    nivel: 'beginner',
    tipoMovimento: 'legs',
    padraoMotor: 'hinge',
    planoMovimento: 'sagittal',
    execucao: 'Com um halter em cada mão nas coxas, projetar o quadril para trás preservando a curvatura natural da coluna.',
    passoAPasso: [
      '1. Segure um halter em cada mão em pegada neutra à frente das coxas.',
      '2. Destrave levemente os joelhos e empurre o quadril para trás de forma fluida.',
      '3. Desça os halteres bem próximos da tíbia e coxas.',
      '4. Interrompa a descida ao sentir o estiramento máximo dos posteriores.',
      '5. Contraia o glúteo e empurre o quadril para a frente para finalizar a repetição.'
    ],
    objetivo: 'Alongamento mecânico seguro e hipertrofia dos isquiotibiais com halteres.',
    dicaPrincipal: 'Mantenha os halteres colados nas pernas durante todo o trajeto.',
    respiracao: 'Inspire na descida, expire na extensão de quadril.',
    amplitude: 'Alongamento máximo dos posteriores.',
    cadencia: '3-0-1-0',
    rir: 2,
    rpe: 8,
    descanso: 90,
    video: 'https://www.youtube-nocookie.com/embed/1uDiW5--rAE',
    youtubeVideoId: '1uDiW5--rAE',
    imagemAnatomica3D: '/images/athletic_hinge_3d_1786106034930.jpg',
    errosComuns: ['Afastar halteres das pernas'],
    variacoes: ['Stiff B-Stance', 'Stiff Sumo'],
    substitutos: [],
    fatigueIndex: 3
  },
  {
    id: 'ex_hip_thrust',
    nome: 'Elevação Pélvica com Barra (Hip Thrust)',
    nomeEnglish: 'Barbell Hip Thrust',
    grupoMuscular: 'gluteos',
    musculosSecundarios: ['posteriores', 'quadriceps'],
    categoria: 'compound',
    equipamento: 'barbell',
    nivel: 'intermediate',
    tipoMovimento: 'legs',
    padraoMotor: 'hinge',
    planoMovimento: 'sagittal',
    execucao: 'Escápulas apoiadas firmemente no banco, barra posicionada na crista ilíaca com acolchoamento. Estender o quadril até alinhamento total com joelho e tronco.',
    passoAPasso: [
      '1. Apoie a parte inferior das escápulas na borda de um banco estofado.',
      '2. Posicione a barra acolchoada exatamente sobre a prega do quadril (crista ilíaca).',
      '3. Mantenha os pés no chão na largura dos ombros com joelhos flexionados a ~90° no topo.',
      '4. Desça o quadril em direção ao chão mantendo o queixo recolhido no peito.',
      '5. Empurre pelos calcanhares elevando o quadril até ficar paralelo ao solo.',
      '6. Esprema os glúteos fortemente no topo por 1 segundo antes de descer.'
    ],
    objetivo: 'Hipertrofia máxima e pico de contração nos glúteos (glúteo máximo).',
    dicaPrincipal: 'Olhe sempre para frente (queixo no peito) para evitar hiperestender a lombar no topo.',
    respiracao: 'Expire forte no topo comprimindo glúteos, inspire ao retornar.',
    amplitude: 'Extensão completa de quadril com 1 segundo de pausa no topo.',
    cadencia: '2-1-1-0',
    rir: 1,
    rpe: 9,
    descanso: 120,
    video: 'https://www.youtube-nocookie.com/embed/SEdqd1n0cvg',
    youtubeVideoId: 'SEdqd1n0cvg',
    imagemAnatomica3D: '/images/athletic_hinge_3d_1786106034930.jpg',
    errosComuns: ['Hiperextensão da lombar no topo', 'Pés muito à frente ou muito atrás'],
    variacoes: ['Hip Thrust Máquina', 'Hip Thrust com Halter', 'Hip Thrust Unilateral'],
    substitutos: [
      { originalId: 'ex_hip_thrust', replacementId: 'ex_glute_bridge_dumbbell', replacementName: 'Ponte de Glúteo no Chão com Halter', condition: 'home', equivalenceScore: 88, notes: 'Ótima alternativa para execução em casa sem banco.' }
    ],
    fatigueIndex: 3
  },
  {
    id: 'ex_lying_leg_curl',
    nome: 'Mesa Flexora',
    nomeEnglish: 'Lying Leg Curl Machine',
    grupoMuscular: 'posteriores',
    musculosSecundarios: [],
    categoria: 'isolation',
    equipamento: 'machine',
    nivel: 'beginner',
    tipoMovimento: 'legs',
    padraoMotor: 'isolation_lower',
    planoMovimento: 'sagittal',
    execucao: 'Deitado em decúbito ventral, rolo ajustado acima dos calcanhares. Flexionar os joelhos até aproximação do glúteo sem elevar o quadril.',
    passoAPasso: [
      '1. Deite-se de bruços na máquina com o eixo do joelho alinhado à rotação do aparelho.',
      '2. Posicione o rolo almofadado logo acima dos calcanhares.',
      '3. Segure as manoplas de apoio para fixar o quadril na almofada.',
      '4. Flexione os joelhos puxando o rolo em direção aos glúteos.',
      '5. Contraia o posterior da coxa no ponto mais alto.',
      '6. Retorne estendendo os joelhos lentamente sob controle excêntrico.'
    ],
    objetivo: 'Isolamento direto da flexão de joelho para hipertrofia de isquiotibiais.',
    dicaPrincipal: 'Não deixe o quadril descolar do estofado durante a subida da carga.',
    respiracao: 'Expire ao flexionar, inspire ao estender controladamente.',
    amplitude: 'Extensão quase total sem perder tensão mecânica.',
    cadencia: '3-0-1-1',
    rir: 1,
    rpe: 9,
    descanso: 75,
    video: 'https://www.youtube-nocookie.com/embed/1Tq3QdYUuHs',
    youtubeVideoId: '1Tq3QdYUuHs',
    imagemAnatomica3D: '/images/athletic_hinge_3d_1786106034930.jpg',
    errosComuns: ['Elevação e rotação pélvica', 'Utilizar impulso de tronco'],
    variacoes: ['Cadeira Flexora', 'Flexão de Joelhos em Pé'],
    substitutos: [
      { originalId: 'ex_lying_leg_curl', replacementId: 'ex_stiff_dumbbell', replacementName: 'Stiff com Halteres', condition: 'small_gym', equivalenceScore: 85, notes: 'Foco no alongamento em vez da flexão pura de joelho.' },
      { originalId: 'ex_lying_leg_curl', replacementId: 'ex_nordic_hamstring', replacementName: 'Flexão Nórdica Corporal', condition: 'home', equivalenceScore: 92, notes: 'Exercício de altíssima ativação eccêntrica.' }
    ],
    fatigueIndex: 2
  },

  // --- HORIZONTAL PUSH (Peitoral, Deltóide Anterior, Tríceps) ---
  {
    id: 'ex_bench_press_barbell',
    nome: 'Supino Reto com Barra',
    nomeEnglish: 'Barbell Bench Press',
    grupoMuscular: 'peitoral',
    musculosSecundarios: ['ombros', 'triceps'],
    categoria: 'compound',
    equipamento: 'barbell',
    nivel: 'intermediate',
    tipoMovimento: 'push',
    padraoMotor: 'horizontal_push',
    planoMovimento: 'sagittal',
    execucao: 'Deitado no banco reto com escápulas aduzidas e deprimidas. Descer a barra até o esterno inferior e empurrar até a extensão dos cotovelos.',
    passoAPasso: [
      '1. Deite-se no banco com os olhos alinhados verticalmente com a barra.',
      '2. Segure a barra com pegada pronada um pouco mais aberta que a largura dos ombros.',
      '3. Aduza e deprima as escápulas (junte os ombros para trás no banco).',
      '4. Retire a barra do suporte e posicione-a sobre o peitoral.',
      '5. Desça a barra de forma controlada até tocar suavemente a linha inferior do peito.',
      '6. Empurre a barra para cima e levemente para trás até alinhar com os ombros.'
    ],
    objetivo: 'Construção muscular de volume e força no peitoral maior, deltóide anterior e tríceps.',
    dicaPrincipal: 'Mantenha as escápulas presas no banco durante todo o movimento para proteger os ombros.',
    respiracao: 'Inspire na descida excêntrica preservando a ponte escapular, expire na subida.',
    amplitude: 'Tocar o esterno com controle mantendo cotovelos a ~45° do tronco.',
    cadencia: '3-0-1-0',
    rir: 2,
    rpe: 8,
    descanso: 120,
    video: 'https://www.youtube-nocookie.com/embed/rT7DgCr-3pg',
    youtubeVideoId: 'rT7DgCr-3pg',
    imagemAnatomica3D: '/images/athletic_bench_3d_1786105975477.jpg',
    errosComuns: ['Cotovelos abertos a 90° (estresse no ombro)', 'Perder adução escapular'],
    variacoes: ['Supino Inclinado com Barra', 'Supino com Halteres'],
    substitutos: [
      { originalId: 'ex_bench_press_barbell', replacementId: 'ex_bench_press_dumbbell', replacementName: 'Supino Reto com Halteres', condition: 'small_gym', equivalenceScore: 96, notes: 'Excelente amplitude e independência dos membros.' },
      { originalId: 'ex_bench_press_barbell', replacementId: 'ex_pushup', replacementName: 'Flexão de Braço (Push-up)', condition: 'home', equivalenceScore: 82, notes: 'Progressão com peso no tronco ou elástico.' }
    ],
    fatigueIndex: 4
  },
  {
    id: 'ex_bench_press_dumbbell',
    nome: 'Supino Reto com Halteres',
    nomeEnglish: 'Dumbbell Bench Press',
    grupoMuscular: 'peitoral',
    musculosSecundarios: ['ombros', 'triceps'],
    categoria: 'compound',
    equipamento: 'dumbbell',
    nivel: 'beginner',
    tipoMovimento: 'push',
    padraoMotor: 'horizontal_push',
    planoMovimento: 'sagittal',
    execucao: 'Com halteres na linha do peito, descer expandindo a caixa torácica e empurrar aproximando os halteres no topo.',
    passoAPasso: [
      '1. Sente-se no banco com um halter apoiado sobre cada coxa.',
      '2. Deite-se empurrando os halteres com as coxas para a posição de início no peitoral.',
      '3. Mantenha os antebraços verticais e as escápulas retraídas contra o banco.',
      '4. Desça os halteres abrindo o peito até sentir bom alongamento no peitoral.',
      '5. Empurre os halteres para cima trazendo-os para o centro sem batê-los.',
      '6. Retorne com descida controlada.'
    ],
    objetivo: 'Maior amplitude de alongamento e ativação independente do peitoral maior.',
    dicaPrincipal: 'Desça os halteres em um ângulo de 45° em relação ao tronco, preservando a articulação do ombro.',
    respiracao: 'Inspire na descida, expire ao empurrar.',
    amplitude: 'Máximo alongamento seguro do peitoral.',
    cadencia: '3-0-1-0',
    rir: 1,
    rpe: 8.5,
    descanso: 90,
    video: 'https://www.youtube-nocookie.com/embed/4Y2ZdHCOXok',
    youtubeVideoId: '4Y2ZdHCOXok',
    imagemAnatomica3D: '/images/athletic_bench_3d_1786105975477.jpg',
    errosComuns: ['Bater os halteres com violência no topo', 'Desalinhar os antebraços da vertical'],
    variacoes: ['Supino Inclinado Halter', 'Supino Declina Halter'],
    substitutos: [],
    fatigueIndex: 3
  },
  {
    id: 'ex_incline_dumbbell_press',
    nome: 'Supino Inclinado com Halteres (30°)',
    nomeEnglish: '30° Incline Dumbbell Press',
    grupoMuscular: 'peitoral',
    musculosSecundarios: ['ombros', 'triceps'],
    categoria: 'compound',
    equipamento: 'dumbbell',
    nivel: 'beginner',
    tipoMovimento: 'push',
    padraoMotor: 'horizontal_push',
    planoMovimento: 'sagittal',
    execucao: 'Banco ajustado a 30° de inclinação. Foco na porção clavicular do peitoral mantendo adução escapular.',
    passoAPasso: [
      '1. Ajuste o banco inclinado em 30 graus.',
      '2. Sente-se e apoie os halteres no peitoral com os cotovelos posicionados a 45°.',
      '3. Mantenha os pés firmes no chão e a lombar com curvatura natural.',
      '4. Desça a carga em direção à porção superior do peito (clavícula).',
      '5. Empurre verticalmente estendendo os cotovelos.',
      '6. Retorne controlando o tempo de descida.'
    ],
    objetivo: 'Desenvolvimento e hipertrofia da porção clavicular (superior) do peitoral maior.',
    dicaPrincipal: 'Não incline o banco acima de 30-45° para evitar transferir todo o trabalho para o ombro.',
    respiracao: 'Inspire na descida, expire na concêntrica.',
    amplitude: 'Tocar levemente a lateral da clavícula com os halteres.',
    cadencia: '3-1-1-0',
    rir: 2,
    rpe: 8,
    descanso: 90,
    video: 'https://www.youtube-nocookie.com/embed/8iPEnn-ltC8',
    youtubeVideoId: '8iPEnn-ltC8',
    imagemAnatomica3D: '/images/athletic_bench_3d_1786105975477.jpg',
    errosComuns: ['Banco muito elevado (virando desenvolvimento de ombro)', 'Cotovelos muito abertos'],
    variacoes: ['Supino Inclinado com Barra', 'Supino Inclinado Máquina'],
    substitutos: [
      { originalId: 'ex_incline_dumbbell_press', replacementId: 'ex_bench_press_dumbbell', replacementName: 'Supino Reto com Halteres', condition: 'small_gym', equivalenceScore: 90, notes: 'Pode ser executado se o banco articulado não estiver livre.' }
    ],
    fatigueIndex: 3
  },
  {
    id: 'ex_cable_fly',
    nome: 'Crucifixo no Crossover (Cabo)',
    nomeEnglish: 'Cable Chest Fly',
    grupoMuscular: 'peitoral',
    musculosSecundarios: ['ombros'],
    categoria: 'isolation',
    equipamento: 'cable',
    nivel: 'beginner',
    tipoMovimento: 'push',
    padraoMotor: 'isolation_upper',
    planoMovimento: 'transverse',
    execucao: 'Polias na altura média ou alta. Abraçar a árvore aproximando as mãos à frente do peito com cotovelos semiflexionados.',
    passoAPasso: [
      '1. Ajuste as polias na altura do peito ou um pouco acima.',
      '2. Segure os pegadores e dê um passo à frente para criar tensão nos cabos.',
      '3. Mantenha os cotovelos levemente flexionados e fixos.',
      '4. Traga as mãos para a frente abraçando o tronco até as mãos se aproximarem.',
      '5. Esprema o peitoral no ponto central de encontro.',
      '6. Abra os braços de forma controlada até sentir o alongamento peitoral.'
    ],
    objetivo: 'Isolamento peitoral com tensão mecânica contínua do início ao fim do movimento.',
    dicaPrincipal: 'Mantenha a flexão dos cotovelos constante — não transforme o movimento em supino!',
    respiracao: 'Expire ao aduzir os ombros, inspire ao abrir.',
    amplitude: 'Tensão mecânica constante no pico de contração.',
    cadencia: '2-1-1-1',
    rir: 1,
    rpe: 9,
    descanso: 60,
    video: 'https://www.youtube-nocookie.com/embed/Iwe6AmxVf7o',
    youtubeVideoId: 'Iwe6AmxVf7o',
    imagemAnatomica3D: '/images/athletic_bench_3d_1786105975477.jpg',
    errosComuns: ['Estender totalmente os cotovelos gerando estresse na articulação'],
    variacoes: ['Peck Deck / Voador', 'Crucifixo Reto Halteres'],
    substitutos: [
      { originalId: 'ex_cable_fly', replacementId: 'ex_peck_deck', replacementName: 'Voador / Peck Deck Máquina', condition: 'small_gym', equivalenceScore: 95, notes: 'Excelente tensão contínua sem necessidade de ajustes em cabos.' },
      { originalId: 'ex_cable_fly', replacementId: 'ex_dumbbell_fly', replacementName: 'Crucifixo Reto com Halteres', condition: 'home', equivalenceScore: 85, notes: 'Substituição com halteres mantendo a adução de ombro.' }
    ],
    fatigueIndex: 1
  },

  // --- HORIZONTAL PULL (Costas, Deltóide Posterior, Bíceps) ---
  {
    id: 'ex_barbell_row',
    nome: 'Remada Curvada com Barra',
    nomeEnglish: 'Barbell Bent-Over Row',
    grupoMuscular: 'costas',
    musculosSecundarios: ['biceps', 'ombros', 'core'],
    categoria: 'compound',
    equipamento: 'barbell',
    nivel: 'intermediate',
    tipoMovimento: 'pull',
    padraoMotor: 'horizontal_pull',
    planoMovimento: 'sagittal',
    execucao: 'Tronco inclinado a ~45° com joelhos flexionados e lombar preservada. Puxar a barra em direção ao umbigo aduzindo as escápulas.',
    passoAPasso: [
      '1. Segure a barra com pegada pronada na largura dos ombros.',
      '2. Incline o tronco para a frente a aproximadamente 45° flexionando o quadril.',
      '3. Mantenha os joelhos destravados e a coluna lombar totalmente neutra.',
      '4. Puxe a barra em direção ao umbigo conduzindo com os cotovelos.',
      '5. Retraia as escápulas no topo da remada.',
      '6. Baixe a barra com controle estendendo completamente os braços.'
    ],
    objetivo: 'Espessura e densidade de toda a musculatura das costas (latíssimo, rombóides e trapézio).',
    dicaPrincipal: 'Puxe o peso mentalizando conduzir os cotovelos para trás, não apenas dobrando as mãos.',
    respiracao: 'Expire na puxada puxando os cotovelos, inspire na extensão dos braços.',
    amplitude: 'Barbell toca o abdômen inferior.',
    cadencia: '2-1-1-0',
    rir: 2,
    rpe: 8,
    descanso: 120,
    video: 'https://www.youtube-nocookie.com/embed/FWJR5Ve8bnQ',
    youtubeVideoId: 'FWJR5Ve8bnQ',
    imagemAnatomica3D: '/images/athletic_row_3d_1786105987331.jpg',
    errosComuns: ['Balançar o tronco para subir o peso (impulso)', 'Tronco muito ereto'],
    variacoes: ['Remada Pendlay', 'Remada Supinada'],
    substitutos: [
      { originalId: 'ex_barbell_row', replacementId: 'ex_dumbbell_row_unilateral', replacementName: 'Remada Unilateral com Halter (Serrote)', condition: 'small_gym', equivalenceScore: 94, notes: 'Apoio no banco elimina fadiga da lombar.' },
      { originalId: 'ex_barbell_row', replacementId: 'ex_seated_cable_row', replacementName: 'Remada Baixa no Crossover', condition: 'full_gym', equivalenceScore: 92, notes: 'Tração em cabo contínua.' }
    ],
    fatigueIndex: 4
  },
  {
    id: 'ex_dumbbell_row_unilateral',
    nome: 'Remada Unilateral com Halter (Serrote)',
    nomeEnglish: 'Single-Arm Dumbbell Row',
    grupoMuscular: 'costas',
    musculosSecundarios: ['biceps', 'ombros'],
    categoria: 'compound',
    equipamento: 'dumbbell',
    nivel: 'beginner',
    tipoMovimento: 'pull',
    padraoMotor: 'horizontal_pull',
    planoMovimento: 'sagittal',
    execucao: 'Um joelho e mão apoiados no banco reto. Puxar o halter conduzindo o cotovelo em arco em direção ao quadril.',
    passoAPasso: [
      '1. Apoie o joelho e a mão do mesmo lado em um banco plano.',
      '2. Mantenha a coluna paralela ao chão e neutra.',
      '3. Segure o halter com a mão livre permitindo o alongamento do dorsal no fundo.',
      '4. Puxe o halter trazendo o cotovelo em direção ao quadril.',
      '5. Contraia a lateral das costas no ponto alto.',
      '6. Desça o halter alongando a escápula sem torcer o tronco.'
    ],
    objetivo: 'Desenvolvimento unilateral do latíssimo do dorso com suporte lombar.',
    dicaPrincipal: 'Faça um movimento em arco puxando para o quadril, não em linha reta vertical para o ombro.',
    respiracao: 'Expire na tração, inspire no alongamento.',
    amplitude: 'Projeção completa da escápula para baixo antes de puxar.',
    cadencia: '2-1-1-0',
    rir: 1,
    rpe: 8.5,
    descanso: 90,
    video: 'https://www.youtube-nocookie.com/embed/roCP6wCXPqo',
    youtubeVideoId: 'roCP6wCXPqo',
    imagemAnatomica3D: '/images/athletic_row_3d_1786105987331.jpg',
    errosComuns: ['Rodar excessivamente o tronco'],
    variacoes: ['Remada Meadow', 'Remada Kroc'],
    substitutos: [],
    fatigueIndex: 2
  },
  {
    id: 'ex_seated_cable_row',
    nome: 'Remada Baixa Sentada no Cabo (Triângulo)',
    nomeEnglish: 'Seated Cable Row',
    grupoMuscular: 'costas',
    musculosSecundarios: ['biceps', 'ombros'],
    categoria: 'compound',
    equipamento: 'cable',
    nivel: 'beginner',
    tipoMovimento: 'pull',
    padraoMotor: 'horizontal_pull',
    planoMovimento: 'sagittal',
    execucao: 'Sentado com joelhos levemente flexionados, puxar a pegada em direção ao abdômen abrindo o peito e retraindo escápulas.',
    passoAPasso: [
      '1. Sente-se na estofamento com os pés apoiados nas plataformas dianteiras.',
      '2. Segure o puxador triângulo mantendo os joelhos confortavelmente flexionados.',
      '3. Mantenha a postura ereta com peito aberto.',
      '4. Puxe a pegada em direção ao umbigo retraindo as escápulas.',
      '5. Pause 1 segundo com o peito estufado.',
      '6. Retorne estendendo os braços e projetando levemente os ombros à frente para alongar.'
    ],
    objetivo: 'Estabilidade mecânica e contração isolada da musculatura média das costas.',
    dicaPrincipal: 'Evite inclinar o tronco para trás e para a frente de forma exagerada durante as repetições.',
    respiracao: 'Expire ao puxar, inspire na fase excêntrica.',
    amplitude: 'Alongamento controlado dos dorsais na ida.',
    cadencia: '2-1-1-0',
    rir: 2,
    rpe: 8,
    descanso: 90,
    video: 'https://www.youtube-nocookie.com/embed/GZbfZ033fBo',
    youtubeVideoId: 'GZbfZ033fBo',
    imagemAnatomica3D: '/images/athletic_row_3d_1786105987331.jpg',
    errosComuns: ['Balanço exagerado para trás'],
    variacoes: ['Remada Baixa Pegada Aberta', 'Remada Unilateral em Cabo'],
    substitutos: [
      { originalId: 'ex_seated_cable_row', replacementId: 'ex_barbell_row', replacementName: 'Remada Curvada com Barra', condition: 'small_gym', equivalenceScore: 90, notes: 'Ótima alternativa com pesos livres.' }
    ],
    fatigueIndex: 2
  },

  // --- VERTICAL PULL (Grande Dorsal, Redondo Maior) ---
  {
    id: 'ex_lat_pulldown',
    nome: 'Puxada Alta pela Frente',
    nomeEnglish: 'Lat Pulldown',
    grupoMuscular: 'costas',
    musculosSecundarios: ['biceps', 'ombros'],
    categoria: 'compound',
    equipamento: 'cable',
    nivel: 'beginner',
    tipoMovimento: 'pull',
    padraoMotor: 'vertical_pull',
    planoMovimento: 'frontal',
    execucao: 'Pegada aberta pronada na barra, puxar em direção ao peitoral superior deprimindo e aduzindo escápulas.',
    passoAPasso: [
      '1. Ajuste os rolos das coxas para manter o corpo bem preso ao assento.',
      '2. Segure a barra com pegada pronada mais aberta que a largura dos ombros.',
      '3. Sente-se mantendo o tronco levemente inclinado para trás (~10-15°).',
      '4. Puxe a barra para baixo em direção ao peitoral superior.',
      '5. Deprima as escápulas trazendo os cotovelos para baixo e para trás.',
      '6. Retorne a barra ao alto estendendo completamente os braços.'
    ],
    objetivo: 'Largura e formato em V (V-taper) do latíssimo do dorso.',
    dicaPrincipal: 'Puxe a barra em direção à clavícula estufando o peito no encontro.',
    respiracao: 'Expire ao puxar a barra até a altura do queixo/clavícula, inspire no retorno.',
    amplitude: 'Extensão total dos braços sem desacoplar os ombros.',
    cadencia: '3-0-1-0',
    rir: 2,
    rpe: 8,
    descanso: 90,
    video: 'https://www.youtube-nocookie.com/embed/CAwf7n6Luuc',
    youtubeVideoId: 'CAwf7n6Luuc',
    imagemAnatomica3D: '/images/athletic_row_3d_1786105987331.jpg',
    errosComuns: ['Puxar atrás do pescoço (estresse cervical)', 'Curvar o peito para dentro'],
    variacoes: ['Puxada Neutra', 'Puxada Supinada', 'Puxada Unilateral'],
    substitutos: [
      { originalId: 'ex_lat_pulldown', replacementId: 'ex_pullup', replacementName: 'Barra Fixa (Pull-up)', condition: 'full_gym', equivalenceScore: 95, notes: 'Excelente exercício calistênico equivalente.' },
      { originalId: 'ex_lat_pulldown', replacementId: 'ex_band_pulldown', replacementName: 'Puxada Alta com Elástico', condition: 'home', equivalenceScore: 80, notes: 'Substituição viável para casa com resistência elástica.' }
    ],
    fatigueIndex: 3
  },
  {
    id: 'ex_pullup',
    nome: 'Barra Fixa Pronada',
    nomeEnglish: 'Bodyweight Pull-Up',
    grupoMuscular: 'costas',
    musculosSecundarios: ['biceps', 'core'],
    categoria: 'compound',
    equipamento: 'bodyweight',
    nivel: 'intermediate',
    tipoMovimento: 'pull',
    padraoMotor: 'vertical_pull',
    planoMovimento: 'frontal',
    execucao: 'Segurar a barra com pegada pronada aberta, elevar o corpo até ultrapassar o queixo pela barra.',
    passoAPasso: [
      '1. Segure na barra fixa com pegada aberta e pronada.',
      '2. Mantenha os braços estendidos e o corpo suspenso.',
      '3. Inicie o movimento puxando os ombros para baixo.',
      '4. Puxe todo o peso do corpo para cima até o queixo passar da linha da barra.',
      '5. Mantenha o core firme e evite balançar as pernas.',
      '6. Controle a descida até o alongamento total.'
    ],
    objetivo: 'Força relativa máxima e expansão dorsal.',
    dicaPrincipal: 'Foque em abaixar as escápulas antes de dobrar os cotovelos.',
    respiracao: 'Expire na subida concêntrica, inspire ao descer.',
    amplitude: 'Extensão completa no fundo até flexão completa no topo.',
    cadencia: '2-1-1-0',
    rir: 2,
    rpe: 8.5,
    descanso: 120,
    video: 'https://www.youtube-nocookie.com/embed/eGo4IYlbE5g',
    youtubeVideoId: 'eGo4IYlbE5g',
    imagemAnatomica3D: '/images/athletic_row_3d_1786105987331.jpg',
    errosComuns: ['Usar impulso das pernas (kipping)', 'Meio movimento'],
    variacoes: ['Chin-up (Pegada Supinada)', 'Barra Graviton (Assistida)'],
    substitutos: [
      { originalId: 'ex_pullup', replacementId: 'ex_lat_pulldown', replacementName: 'Puxada Alta pela Frente', condition: 'small_gym', equivalenceScore: 96, notes: 'Permite regular a carga exata adequada ao nível.' }
    ],
    fatigueIndex: 4
  },

  // --- VERTICAL PUSH (Deltóides & Tríceps) ---
  {
    id: 'ex_overhead_press_barbell',
    nome: 'Desenvolvimento de Ombro com Barra (OHP)',
    nomeEnglish: 'Barbell Overhead Press',
    grupoMuscular: 'ombros',
    musculosSecundarios: ['triceps', 'core', 'peitoral'],
    categoria: 'compound',
    equipamento: 'barbell',
    nivel: 'intermediate',
    tipoMovimento: 'push',
    padraoMotor: 'vertical_push',
    planoMovimento: 'sagittal',
    execucao: 'Em pé ou sentado, barra na altura da clavícula. Empurrar a barra verticalmente acima da cabeça bloqueando o glúteo e abdômen.',
    passoAPasso: [
      '1. Remova a barra do suporte ajustado na altura dos ombros.',
      '2. Apoie a barra na frente dos ombros e clavículas com pegada um pouco mais aberta que a largura dos ombros.',
      '3. Contraia o abdômen e os glúteos de forma bem firme.',
      '4. Empurre a barra verticalmente passando rente ao rosto.',
      '5. Assim que a barra passar pela cabeça, projete o tronco levemente à frente para alinhar a barra com os ombros.',
      '6. Retorne com descida controlada até o peito.'
    ],
    objetivo: 'Força bruta e volume nos ombros (deltóide anterior e lateral) e estabilização do tronco.',
    dicaPrincipal: 'Não dobre os joelhos durante a subida para não transformar o exercício em Push Press.',
    respiracao: 'Inspire na base, expire ao ultrapassar a cabeça estendendo os braços.',
    amplitude: 'Da clavícula até o bloqueio seguro acima da cabeça.',
    cadencia: '3-0-1-0',
    rir: 2,
    rpe: 8,
    descanso: 120,
    video: 'https://www.youtube-nocookie.com/embed/2yjwXTZQDDI',
    youtubeVideoId: '2yjwXTZQDDI',
    imagemAnatomica3D: '/images/athletic_overhead_3d_1786105999818.jpg',
    errosComuns: ['Hiperextensão da coluna lombar por falta de estabilização do core', 'Inclinar para trás virando supino'],
    variacoes: ['Desenvolvimento com Halteres Sentado', 'Desenvolvimento Arnold'],
    substitutos: [
      { originalId: 'ex_overhead_press_barbell', replacementId: 'ex_overhead_press_dumbbell', replacementName: 'Desenvolvimento Sentado com Halteres', condition: 'small_gym', equivalenceScore: 95, notes: 'Maior liberdade para rotação dos ombros.' }
    ],
    fatigueIndex: 4
  },
  {
    id: 'ex_overhead_press_dumbbell',
    nome: 'Desenvolvimento Sentado com Halteres',
    nomeEnglish: 'Seated Dumbbell Shoulder Press',
    grupoMuscular: 'ombros',
    musculosSecundarios: ['triceps'],
    categoria: 'compound',
    equipamento: 'dumbbell',
    nivel: 'beginner',
    tipoMovimento: 'push',
    padraoMotor: 'vertical_push',
    planoMovimento: 'frontal',
    execucao: 'Sentado no banco a 85-90°. Halteres na altura das orelhas, empurrar para cima em arco suave até quase se tocarem no topo.',
    passoAPasso: [
      '1. Sente-se no banco com encosto ajustado a 80-90°.',
      '2. Eleve os halteres até a altura da orelha e dos ombros.',
      '3. Mantenha as escápulas firme no encosto e os cotovelos a 45°.',
      '4. Empurre os halteres para cima em direção ao topo da cabeça.',
      '5. Estenda os braços sem travar bruscamente os cotovelos.',
      '6. Controle a descida até a altura do queixo.'
    ],
    objetivo: 'Desenvolvimento hipertrófico da massa muscular dos ombros.',
    dicaPrincipal: 'Mantenha os cotovelos ligeiramente à frente do corpo em vez de totalmente abertos para os lados.',
    respiracao: 'Inspire embaixo, expire ao empurrar.',
    amplitude: 'Descer até o nível do queixo/ombros.',
    cadencia: '3-0-1-0',
    rir: 2,
    rpe: 8,
    descanso: 90,
    video: 'https://www.youtube-nocookie.com/embed/qEwKCR5JCog',
    youtubeVideoId: 'qEwKCR5JCog',
    imagemAnatomica3D: '/images/athletic_overhead_3d_1786105999818.jpg',
    errosComuns: ['Descer halteres assimetricamente'],
    variacoes: ['Desenvolvimento Unilateral', 'Desenvolvimento Arnold'],
    substitutos: [],
    fatigueIndex: 2
  },
  {
    id: 'ex_lateral_raise_dumbbell',
    nome: 'Elevação Lateral com Halteres',
    nomeEnglish: 'Dumbbell Lateral Raise',
    grupoMuscular: 'ombros',
    musculosSecundarios: [],
    categoria: 'isolation',
    equipamento: 'dumbbell',
    nivel: 'beginner',
    tipoMovimento: 'push',
    padraoMotor: 'isolation_upper',
    planoMovimento: 'frontal',
    execucao: 'Em pé ou sentado, elevar os halteres no plano escapular (~30° à frente do corpo) até a altura dos ombros.',
    passoAPasso: [
      '1. Em pé ou sentado, segure um halter em cada mão ao lado do tronco.',
      '2. Mantenha os joelhos destravados e o tronco levemente inclinado à frente (5°).',
      '3. Eleve os halteres para os lados no plano escapular (30° à frente do corpo).',
      '4. Suba até que as mãos fiquem na linha dos ombros.',
      '5. Mantenha o dedinho do pé do halter ligeiramente mais alto que o polegar.',
      '6. Desça resistindo à gravidade em 2 a 3 segundos.'
    ],
    objetivo: 'Isolamento estético e expansão lateral do deltóide médio (ombros largos).',
    dicaPrincipal: 'Pense em empurrar as cargas para longe do corpo e para os lados, não em encolher o pescoço.',
    respiracao: 'Expire ao subir, inspire ao descer.',
    amplitude: 'Até a linha horizontal dos ombros.',
    cadencia: '2-1-1-1',
    rir: 1,
    rpe: 9,
    descanso: 60,
    video: 'https://www.youtube-nocookie.com/embed/3VcKaXpzqRo',
    youtubeVideoId: '3VcKaXpzqRo',
    imagemAnatomica3D: '/images/athletic_overhead_3d_1786105999818.jpg',
    errosComuns: ['Usar impulso das pernas', 'Encolher os ombros ativando excessivamente o trapézio'],
    variacoes: ['Elevação Lateral no Crossover', 'Elevação Lateral Inclinada'],
    substitutos: [
      { originalId: 'ex_lateral_raise_dumbbell', replacementId: 'ex_lateral_raise_cable', replacementName: 'Elevação Lateral no Cabo (Polia Baixa)', condition: 'full_gym', equivalenceScore: 98, notes: 'Tensão uniforme em toda a curva de força.' }
    ],
    fatigueIndex: 1
  },

  // --- ISOLATION & CORE (Bíceps, Tríceps, Panturrilha, Core) ---
  {
    id: 'ex_biceps_curl_barbell',
    nome: 'Rosca Direta com Barra W',
    nomeEnglish: 'EZ-Bar Biceps Curl',
    grupoMuscular: 'biceps',
    musculosSecundarios: [],
    categoria: 'isolation',
    equipamento: 'barbell',
    nivel: 'beginner',
    tipoMovimento: 'pull',
    padraoMotor: 'isolation_upper',
    planoMovimento: 'sagittal',
    execucao: 'Cotovelos fixos ao lado do tronco, flexionar os braços contraindo o bíceps com barra W.',
    passoAPasso: [
      '1. Segure a barra W nas empunhaduras anguladas com as palmas voltadas para cima.',
      '2. Mantenha os cotovelos colados ao lado das costelas e o corpo firme.',
      '3. Flexione os cotovelos puxando a barra em direção ao peito.',
      '4. Contraia o bíceps no ponto mais alto.',
      '5. Desça a barra estendendo os braços com controle total.',
      '6. Evite jogar o tronco para trás na subida.'
    ],
    objetivo: 'Hipertrofia direta e volume dos flexores do cotovelo (bíceps braquial).',
    dicaPrincipal: 'Trave os cotovelos ao lado das costelas durante toda a série.',
    respiracao: 'Expire na subida, inspire na descida excêntrica.',
    amplitude: 'Extensão quase total sem perder tensão no cotovelo.',
    cadencia: '3-0-1-0',
    rir: 1,
    rpe: 8.5,
    descanso: 60,
    video: 'https://www.youtube-nocookie.com/embed/kwG2ipFRgfo',
    youtubeVideoId: 'kwG2ipFRgfo',
    imagemAnatomica3D: '/images/athletic_arms_3d_1786106010485.jpg',
    errosComuns: ['Projetar os cotovelos para frente', 'Jogar a lombar para trás'],
    variacoes: ['Rosca Alternada com Halteres', 'Rosca Martelo'],
    substitutos: [
      { originalId: 'ex_biceps_curl_barbell', replacementId: 'ex_biceps_curl_dumbbell', replacementName: 'Rosca Direta com Halteres', condition: 'small_gym', equivalenceScore: 95, notes: 'Permite supinação ativa do punho durante a subida.' }
    ],
    fatigueIndex: 1
  },
  {
    id: 'ex_triceps_pushdown_cable',
    nome: 'Tríceps Pulley na Polia (Corda ou Barra)',
    nomeEnglish: 'Cable Triceps Pushdown',
    grupoMuscular: 'triceps',
    musculosSecundarios: [],
    categoria: 'isolation',
    equipamento: 'cable',
    nivel: 'beginner',
    tipoMovimento: 'push',
    padraoMotor: 'isolation_upper',
    planoMovimento: 'sagittal',
    execucao: 'Cotovelos colados nas costelas, estender os braços para baixo até o bloqueio completo do tríceps.',
    passoAPasso: [
      '1. Fique em frente à polia alta segurando a corda ou barra.',
      '2. Posicione os cotovelos colados na lateral do tronco.',
      '3. Estenda os braços empurrando a carga para baixo até o final.',
      '4. Esprema os tríceps na extensão completa.',
      '5. Deixe a carga subir flexionando os cotovelos até um ângulo de 90°.',
      '6. Mantenha o ombro estático durante todo o movimento.'
    ],
    objetivo: 'Isolamento e hipertrofia da cabeça lateral e medial do tríceps.',
    dicaPrincipal: 'Foque em mover apenas os antebraços mantendo o braço (úmero) completamente parado.',
    respiracao: 'Expire ao empurrar para baixo, inspire na flexão de cotovelos.',
    amplitude: 'Flexão até 90° e extensão total.',
    cadencia: '2-0-1-1',
    rir: 1,
    rpe: 9,
    descanso: 60,
    video: 'https://www.youtube-nocookie.com/embed/2-LAMcpzODU',
    youtubeVideoId: '2-LAMcpzODU',
    imagemAnatomica3D: '/images/athletic_arms_3d_1786106010485.jpg',
    errosComuns: ['Afastar cotovelos do corpo', 'Usar peso do ombro para esmagar a carga'],
    variacoes: ['Tríceps Testa com Barra W', 'Tríceps Coice'],
    substitutos: [
      { originalId: 'ex_triceps_pushdown_cable', replacementId: 'ex_triceps_skullcrusher', replacementName: 'Tríceps Testa com Halter', condition: 'small_gym', equivalenceScore: 92, notes: 'Ótima sobrecarga na porção longa do tríceps.' }
    ],
    fatigueIndex: 1
  },
  {
    id: 'ex_calf_raise_standing',
    nome: 'Gêmeos em Pé (Panturrilha)',
    nomeEnglish: 'Standing Calf Raise',
    grupoMuscular: 'panturrilhas',
    musculosSecundarios: [],
    categoria: 'isolation',
    equipamento: 'machine',
    nivel: 'beginner',
    tipoMovimento: 'legs',
    padraoMotor: 'isolation_lower',
    planoMovimento: 'sagittal',
    execucao: 'Ponta dos pés na borda do degrau/plataforma, joelhos quase estendidos. Descer o calcanhar até máximo alongamento do sóleo e gastrocnêmio e subir até a ponta máxima dos pés com 1s de pausa.',
    passoAPasso: [
      '1. Apoie a parte anterior dos pés no degrau da plataforma.',
      '2. Mantenha os joelhos quase totalmente estendidos (não flexionados).',
      '3. Desça os calcanhares lentamente abaixo do nível da plataforma sentindo o alongamento máximo.',
      '4. Pause por 1 segundo na posição inferior para dissipar a energia elástica do tendão.',
      '5. Suba impulsionando a carga até a ponta máxima dos pés.',
      '6. Segure a contração no topo por 1 segundo.'
    ],
    objetivo: 'Hipertrofia e fortalecimento do gastrocnêmio e sóleo (panturrilha).',
    dicaPrincipal: 'Faça pausas de 1 segundo embaixo e em cima para forçar o músculo a trabalhar sem quicar.',
    respiracao: 'Expire na subida (plantarflexão), inspire no alongamento.',
    amplitude: 'Máxima flexão e extensão plantar com isometria no topo.',
    cadencia: '2-1-1-1',
    rir: 1,
    rpe: 9,
    descanso: 60,
    video: 'https://www.youtube-nocookie.com/embed/-M4-G8p8fmc',
    youtubeVideoId: '-M4-G8p8fmc',
    imagemAnatomica3D: '/images/athletic_squat_3d_1786105958653.jpg',
    errosComuns: ['Quicar no fundo usando elasticidade do tendão de Aquiles'],
    variacoes: ['Panturrilha no Leg Press', 'Panturrilha Sentado (Sóleo)'],
    substitutos: [],
    fatigueIndex: 1
  },
  {
    id: 'ex_plank',
    nome: 'Prancha Abdominal Isométrica',
    nomeEnglish: 'Plank Core Hold',
    grupoMuscular: 'core',
    musculosSecundarios: ['ombros', 'gluteos'],
    categoria: 'isolation',
    equipamento: 'bodyweight',
    nivel: 'beginner',
    tipoMovimento: 'core',
    padraoMotor: 'core',
    planoMovimento: 'multiplanar',
    execucao: 'Antebraços e ponta dos pés no chão. Manter alinhamento entre cabeça, tronco e quadril contraindo glúteos e transverso do abdômen.',
    passoAPasso: [
      '1. Deite-se de barriga para baixo e apoie os antebraços no chão alinhados com os ombros.',
      '2. Apoie as pontas dos pés no solo afastadas na largura do quadril.',
      '3. Eleve o corpo forming uma linha reta dos calcanhares até a cabeça.',
      '4. Contraia fortemente o transverso do abdômen, glúteos e quadríceps.',
      '5. Mantenha o olhar apontado para o chão.',
      '6. Sustente a posição durante o tempo determinado mantendo a respiração fluida.'
    ],
    objetivo: 'Estabilidade antiextensão do core, fortalecimento do transverso abdominal e proteção lombar.',
    dicaPrincipal: 'Imagine puxar o umbigo em direção à coluna durante toda a sustentação.',
    respiracao: 'Respiração curta e ritmada mantendo o abdômen tensionado.',
    amplitude: 'Sustentação isométrica por tempo determinado.',
    cadencia: 'Isométrico',
    rir: 2,
    rpe: 8,
    descanso: 60,
    video: 'https://www.youtube-nocookie.com/embed/pSHjTRCQxIw',
    youtubeVideoId: 'pSHjTRCQxIw',
    imagemAnatomica3D: '/images/athletic_arms_3d_1786106010485.jpg',
    errosComuns: ['Deixar o quadril cair (hiperextensão lombar)', 'Elevar o bumbum excessivamente'],
    variacoes: ['Prancha Dinâmica', 'Prancha Lateral', 'Abdominal Supra Carenado'],
    substitutos: [],
    fatigueIndex: 1
  }
];

// Algorithmically generate 300+ equipment replacement maps & alternative rules
export function getSmartReplacements(
  exercise: Exercise,
  environment: GymEnvironment,
  forbidden: string[] = []
): Exercise[] {
  // If forbidden or environment constraint, find best matches
  const candidateMatches = EXERCISE_DATABASE.filter(e => {
    if (e.id === exercise.id) return false;
    if (forbidden.includes(e.id) || forbidden.includes(e.nome)) return false;

    // Filter environment capability
    if (environment === 'home' && (e.equipamento === 'machine' || e.equipamento === 'smith')) {
      return false;
    }
    if (environment === 'small_gym' && e.equipamento === 'smith') {
      return false;
    }

    // Match movement pattern or primary muscle group
    return e.padraoMotor === exercise.padraoMotor || e.grupoMuscular === exercise.grupoMuscular;
  });

  // Sort by equivalence
  return candidateMatches.sort((a, b) => {
    let scoreA = 0;
    let scoreB = 0;

    if (a.padraoMotor === exercise.padraoMotor) scoreA += 40;
    if (b.padraoMotor === exercise.padraoMotor) scoreB += 40;

    if (a.grupoMuscular === exercise.grupoMuscular) scoreA += 30;
    if (b.grupoMuscular === exercise.grupoMuscular) scoreB += 30;

    if (a.categoria === exercise.categoria) scoreA += 20;
    if (b.categoria === exercise.categoria) scoreB += 20;

    return scoreB - scoreA;
  });
}
